### ISSUE TITLE
Seed files not properly dropping and reseeding. 

### ISSUE THREAD

**Issue by samuelssnider** [dphilla/quantified-self-node#5]
When running the seed files to re-seed the database, error:
```
error: delete from "foods" - update or delete on table "foods" violates foreign key constraint "meal_foods_food_id_fkey" on table "meal_foods"
    at Connection.parseE (/Users/samuelsnider/turing/4module/projects/quantified-self-node/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/Users/samuelsnider/turing/4module/projects/quantified-self-node/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/Users/samuelsnider/turing/4module/projects/quantified-self-node/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

**Comment by samuelssnider** [comment]
Fixed in : https://github.com/dphilla/quantified-self-node/pull/6
